server:
  port: 9000

spring:
  profiles:
    active: dev

oauth:
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
  
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    
---

spring:
  config:
    activate:
      on-profile: dev
      
  flyway:
    enabled: true
    
  datasource:
    url: jdbc:mysql://${MYSQL_AUTH_HOST}/${AUTH_DATABASE}
    username: ${MYSQL_AUTH_USERNAME}
    password: ${MYSQL_AUTH_PASSWORD}
    
rsa:
  private-key:
    path: keys/cosc411/authorization-server/prod/private.key
  public-key:
    path: keys/cosc411/authorization-server/prod/public.key
      
---

spring:
  config:
    activate:
      on-profile: test
      
  flyway:
    enabled: true
      
  datasource:
    url: jdbc:mysql://${MYSQL_AUTH_HOST_TEST}/${AUTH_DATABASE}
    username: ${MYSQL_AUTH_USERNAME}
    password: ${MYSQL_AUTH_PASSWORD}
    
rsa:
  private-key:
    path: keys/cosc411/authorization-server/test/private.key
  public-key:
    path: keys/cosc411/authorization-server/test/public.key